name: build

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build site
        uses: ghacts/static-site@main
        env:
          DOCSEARCH_APP_ID: ${{ secrets.DOCSEARCH_APP_ID }}
          DOCSEARCH_API_KEY: ${{ secrets.DOCSEARCH_API_KEY }}
          DOCSEARCH_INDEX_NAME: ${{ secrets.DOCSEARCH_INDEX_NAME }}
          GA_ID: ${{ secrets.GA_ID }}
        with:
          node-version: 18
          skip-test: true
          output-dir: 'content/.vuepress/dist'
