name: deploy

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Build site
        uses: ghacts/static-site@main
        env:
          DOCSEARCH_APP_ID: ${{ secrets.DOCSEARCH_APP_ID }}
          DOCSEARCH_API_KEY: ${{ secrets.DOCSEARCH_API_KEY }}
          DOCSEARCH_INDEX_NAME: ${{ secrets.DOCSEARCH_INDEX_NAME }}
          GA_ID: ${{ secrets.GA_ID }}
        with:
          node-version: 18
          skip-test: true
          output-dir: content/.vuepress/dist

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: content/.vuepress/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
